### PR TITLE
align the hero section, create animations and improve the padding of b…

### PR DESCRIPTION
**Pull request by kratigoyal34**
@surajsharma14  please merge my pr as I done my best to contribute in your project. I hope you like it and I made a lot of small changes that I haven't mention in this comment I hope you notice it.

create animation in nav-items, button and user card.
Screenshot 2023-10-28 231103

Screenshot 2023-10-28 231121

Screenshot 2023-10-28 231152

This is the final look of the hero section after correcting the margin.

Screenshot 2023-10-28 231359

### CODE REVIEW

**Comment by surajsharma14** [comment]
@kratigoyal34 Good work. I looking forward to merge it. but before that make sure you follow me so that it will be cunted in valid contribution and accepted by hacktoberfest. 

when you done let me know drop a msg to me in any social handle i will be merge it

**Comment by kratigoyal34** [comment]
@surajsharma14  done now I follow 
 merge my contribution please.

**Comment by surajsharma14** [comment]
@kratigoyal34 your code is PR is conflicts.

**Comment by kratigoyal34** [comment]
@surajsharma14  conflict resolve now you can merge.

**Comment by surajsharma14** [comment]
done

**Pull request merged**
