### PR TITLE
other_products

### PR DESCRIPTION
**Pull request by Shraddha16092002**
added other products section

### CODE REVIEW

**Comment by surajsharma14** [comment]
follow me on github

**Comment by Shraddha16092002** [comment]
> follow me on github

Yes followed!! 
merge my pull request..
Thank you!

**Comment by Shraddha16092002** [comment]
> follow me on github

hello,
I have added other products section.
please merge it in your project. 
Thank you!

**Comment by surajsharma14** [comment]
@Shraddha16092002 your PR is conflicts . try to contribute simple web dev project in my other web development repos. and let me know then i will be merge it.

**Pull request closed without merging**
